name: Docker build
description: This action will build a docker image and push it to Github registry
author: Kapitol
inputs:
  depot_project_id:
    description: Depot Project ID
    required: true
  dockerfile_path:
    description: Dockerfile path including the file name
    required: true
  image_tags:
    description: List of Image tags (CSV)
    required: true
  build_context:
    description: Docker build context
    required: true
    default: ''
  build_args:
    description: Docker build arguments
    required: false
    default: ''
  platforms:
    description: Image supported platforms
    required: false
    default: 'linux/amd64,linux/arm64'
runs:
  using: 'composite'
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.SERVICE_ACCOUNT_USERNAME }}
        password: ${{ env.REGISTRY_TOKEN }}

    - name: Set up Depot CLI
      uses: depot/setup-action@v1

    - name: Run docker build
      uses: depot/build-push-action@v1
      with:
        project: ${{ inputs.DEPOT_PROJECT_ID }}
        build-args: ${{ inputs.build_args }}
        context: ${{ inputs.build_context }}
        platforms: ${{ inputs.platforms }}
        push: true
        file: ${{ inputs.dockerfile_path }}
        tags: ${{ inputs.image_tags }}
